### ISSUE TITLE
Protocol version mismatch

### ISSUE THREAD

**Issue by JulianTrummer** [compas-rrc/compas_rrc_ros#7]
A protocol version mismatch error with our custom docker file for an ABB CRB15000 that we simply didn't manage to solve. It is possible to connect to the ABB client, but at the first abb.send_and_wait command an exception is raised. E.g. trying to run the welcome.py file from the compas_rrc_start repository, the error message reads as follows:

```
(ffc2) C:\Users\julia\workspace\projects>C:/Users/julia/Anaconda3/envs/ffc2/python.exe c:/Users/julia/workspace/projects/compas_rrc_start/Python/welcome.py
Connected.
Traceback (most recent call last):
  File "c:\Users\julia\workspace\projects\compas_rrc_start\Python\welcome.py", line 14, in <module>
    done = abb.send_and_wait(rrc.PrintText('Welcome to my COMPAS_RRC'))
  File "C:\Users\julia\Anaconda3\envs\ffc2\lib\site-packages\compas_rrc\client.py", line 253, in send_and_wait
    future = self.send(instruction)
  File "C:\Users\julia\Anaconda3\envs\ffc2\lib\site-packages\compas_rrc\client.py", line 203, in send
    self.ensure_protocol_version()
  File "C:\Users\julia\Anaconda3\envs\ffc2\lib\site-packages\compas_rrc\client.py", line 146, in ensure_protocol_version
    raise Exception('Protocol version mismatch. Server={}, Client={}'.format(self._server_protocol_check['version'], CLIENT_PROTOCOL_VERSION))
Exception: Protocol version mismatch. Server=None, Client=2
```

All files, including docker, can be found in the following [repository](https://github.com/augmentedfabricationlab/crb15000_fabrication_control).

How can we fix this issue?

**Comment by fleischp** [comment]
Hi Julian, thanks for your feedback.
